# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 177865682799.dkr.ecr.eu-central-1.amazonaws.com/nginx-sample
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: 
    traefik.ingress.kubernetes.io/service-weights: |
      service1: 90%
      service-canary: 10%
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  paths: 
    - backend:
        serviceName: service1
        servicePort: 80
    - backend:
        serviceName: service-canary
        servicePort: 80
  hosts:
    - nginx-sample.dev.mgmt.aws-arvato.com.
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
