{{- if .Values.image.canary.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-helm-chart.fullname" . }}-canary
  labels:
    app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}-canary
    helm.sh/chart: {{ include "nginx-helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-canary
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}-canary
      app.kubernetes.io/instance: {{ .Release.Name }}-canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}-canary
        app.kubernetes.io/instance: {{ .Release.Name }}-canary
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.canary.repository }}:{{ .Values.image.canary.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}