{{- if .Values.image.canary.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-helm-chart.fullname" . }}-canary
  labels:
    app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}-canary
    helm.sh/chart: {{ include "nginx-helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-canary
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}-canary
    app.kubernetes.io/instance: {{ .Release.Name }}-canary
{{- end -}}